name: Node.js Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    defaults:
      run:
        working-directory: react-static-web-apps-auth
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node-version: [10.x, 12.x, 14.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    
  package:
    defaults:
      run:
        working-directory: react-static-web-apps-auth
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - run: npm ci
      - run: npm run build
      - run: npm version perrelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      - run: npm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: "react-static-web-apps-auth/*.tgz"
      
  publish:
    name: "Publish to Github Packages"
    needs: [package]
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'htclorina'
    steps:
      - name: Upload
        uses: actions.download/artifact@v2
        with: 
          name: package
      - uses: actions.setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: "@htclorina"
      - run: echo "registry=https://npm.pkg.github.com/@htclorina" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
